animal_details/urls.py
from django.conf.urls import url
from . import views

app_name='animal_details'
urlpatterns = [

    url(r'^home/$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^$', views.index,name='index'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'animal/add/$',views.AnimalCreate.as_view(),name='animal-add'),

    url(r'animal/(?P<pk>[0-9]+)/$', views.AnimalUpdate.as_view(), name='animal-update'),

    url(r'animal/(?P<pk>[0-9]+)/delete/$', views.AnimalDelete.as_view(), name='animal-delete'),

    url(r'medicines/$',views.med_detail,name='med-detail'),
    url(r'medicines/add/$',views.MedicineCreate.as_view(),name='medicine-add'),
    url(r'medicines/(?P<pk>[0-9]+)/$',views.MedicineUpdate.as_view(),name='medicine-update'),

   
    #/Staff/
    url(r'Staff/$',views.StaffDetail.as_view(),name='Staff-detail'),
    #/Staff/add/
    url(r'Staff/add/$', views.StaffCreate.as_view(),name='Staff-add'),
    #/Staff/pk/
    url(r'Staff/(?P<pk>[0-9]+)/$', views.StaffUpdate.as_view(), name='Staff-update'),
     url(r'Staff/(?P<pk>[0-9]+)/delete/$', views.StaffDelete.as_view(), name='Staff-delete'),

    #/Tourist/
    url(r'Tourist/$',views.TouristDetail.as_view(),name='Tourist-detail'),
    #/Tourist/add/
    url(r'Tourist/add/$', views.TouristCreate.as_view(),name='Tourist-add'),
    #/Tourist/pk/
    url(r'Tourist/(?P<pk>[0-9]+)/$', views.TouristUpdate.as_view(), name='Tourist-update'),


    url(r'account/$',views.AccountDetail.as_view(),name='acc-detail'),
    url(r'account/add/$', views.add_account, name='account-add'),
    url(r'account/(?P<pk>[0-9]+)/$',views.AccountUpdate.as_view(),name='account-update'),
    url(r'account/(?P<pk>[0-9]+)/delete/$', views.AccountDelete.as_view(), name='account-delete'),

    url(r'Organisation_grants/$',views.GrantsDetail.as_view(),name='grant-detail'),
    url(r'Organisation_grants/add/$',views.GrantsCreate.as_view(),name='Org-grant-add'),
    url(r'Organisation_grants/(?P<pk>[0-9]+)/$',views.GrantsUpdate.as_view(),name='grant-Update'),
    url(r'Organisation_grants/(?P<pk>[0-9]+)/delete/$', views.GrantsDelete.as_view(), name='grant-delete'),


     ]

wildlife_sanctuary/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'Sanctuary/',include('animal_details.urls')),
]

if settings.DEBUG:
	urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

animal_details/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Animal(models.Model):
    id=models.AutoField(primary_key=True)
    Animal_species=models.CharField(max_length=100)
    Animal_count=models.IntegerField(default=0)
    Animal_type=models.CharField(max_length=20)
    Scientific_name=models.CharField(max_length=100)
    Country=models.CharField(max_length=100)
    Animal_feed=models.CharField(max_length=100)
    Feed_cost=models.FloatField(default=0)
    Animal_image=models.FileField(null=True,blank=True)
 
    def get_absolute_url(self):
        return reverse('animal_details:detail',kwargs={'pk':self.pk})

    def __str__(self):
        return str(self.id)+' - '+(self.Animal_species)

class Medicine(models.Model):
    Animal_id=models.ForeignKey(Animal,on_delete=models.CASCADE)
    Medicine_name=models.CharField(max_length=200)
    Medicine_cost=models.FloatField(default=0.0)
    Date=models.DateField(auto_now=True)

    def get_absolute_url(self):
        return reverse('animal_details:med-detail')

    def __str__(self):

        return str(self.Animal_id)+' on '+str(self.Date)

class Accounts(models.Model):
    id=models.AutoField(primary_key=True)
    Date=models.DateField(auto_now=True)
    Income=models.FloatField(default=0.0)
    Expenditure=models.FloatField(default=0.0)

    def get_absolute_url(self):
        return reverse('animal_details:acc-detail')

    def __str__(self):
        return str(self.id)+' on '+str(self.Date)

class Organisation_grants(models.Model):
    id=models.AutoField(primary_key=True)
    Organisation_name=models.CharField(max_length=200)
    Organisation_phno=models.CharField(max_length=20)
    Address=models.CharField(max_length=300)
    Amount=models.FloatField(default=0.0)
    Date=models.DateField(auto_now=True)

    def get_absolute_url(self):
        return reverse('animal_details:grant-detail',kwargs={'pk':self.pk})

    def __str__(self):
         return str(self.Organisation_name)+' - '+(self.Amount)



class Staff(models.Model):
    id=models.AutoField(primary_key=True)
    Staff_Name=models.CharField(max_length=100)
    Designation=models.CharField(max_length=50)
    Salary=models.FloatField(default=0.0)

    def get_absolute_url(self):
        return reverse('animal_details:Staff-detail')

    def __str__(self):
         return str(self.id)+' - '+self.Staff_Name


class Tourists(models.Model):
    id=models.AutoField(primary_key=True)
    Tourists_name=models.CharField(max_length=100)
    Donation=models.FloatField(default=0.0)
    Date=models.DateField(auto_now=True)
    GuideName=models.CharField(max_length=100)
    Phone_number=models.IntegerField(default=0)
    Entryfee=models.IntegerField(default=200)


    def get_absolute_url(self):
        return reverse('animal_details:Tourist-detail')

    def __str__(self):
         return str(self.id)+' - '+(self.Tourists_name)

   

animal_details/forms.py
from django import forms
from django.contrib.auth.models import User







class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

animal_details/views.py
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views import generic
from .models import Animal,Medicine,Accounts,Organisation_grants,Staff,Tourists
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy

from .forms import  UserForm
from django.shortcuts import render,get_object_or_404
from django.conf import settings



user=authenticate(username='a',password='1')

from django.db.models import Sum


def add_account(request):
     acc=Accounts()
     don=Tourists.objects.aggregate(Sum('Donation'))
     amt=Organisation_grants.objects.aggregate(Sum('Amount'))
     acc.Income=don['Donation__sum']+amt['Amount__sum']
     sal=Staff.objects.aggregate(Sum('Salary'))
     med=Medicine.objects.aggregate(Sum('Medicine_cost'))
     feed=Animal.objects.aggregate(Sum('Feed_cost'))
     acc.Expenditure=sal['Salary__sum']+med['Medicine_cost__sum']+feed['Feed_cost__sum']
     acc.save()
     new_account=Accounts.objects.all()
     return render(request, 'animal_details/account.html', {'new_account':new_account})

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                animal=Animal.objects.all()
               
                return render(request, 'animal_details/index1.html', {'animals': animal})
    context = {
        "form": form,
    }
    return render(request, 'animal_details/register.html', context)


def home(request):
   
    return render(request,'animal_details/home.html')




def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                animal=Animal.objects.all()
               
                return render(request, 'animal_details/index1.html', {'animals': animal})
               
            else:
                return render(request, 'animal_details/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'animal_details/login.html', {'error_message': 'Invalid login'})
    return render(request, 'animal_details/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'animal_details/home.html', context)



def index(request):
    if not request.user.is_authenticated():
        return render(request, 'animal_details/login.html')
    else:
        animal=Animal.objects.all()
        return render(request, 'animal_details/index1.html', {'animals': animal})
               

def med_detail(request):
    if not request.user.is_authenticated():
        return render(request, 'animal_details/login.html')
    else:
        medicine=Medicine.objects.all()
        return render(request, 'animal_details/med.html', {'medicines':medicine})





               








class DetailView(LoginRequiredMixin,generic.DetailView):
     login_url =None
     
     redirect_unauthenticated_users=False
     raise_exception=False
   
     model = Animal
     template_name = 'animal_details/detail.html'


     


   
#-----------------------------------------------------------------------------------------------------------------------

class AnimalCreate(LoginRequiredMixin,CreateView):

    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
    model = Animal
    fields = ['id', 'Animal_species', 'Animal_count', 'Animal_type', 'Scientific_name', 'Country', 'Animal_feed','Feed_cost','Animal_image']

class AnimalUpdate(LoginRequiredMixin,UpdateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model = Animal
    fields = ['id', 'Animal_species', 'Animal_count', 'Animal_type', 'Scientific_name', 'Country', 'Animal_feed','Feed_cost']

class AnimalDelete(LoginRequiredMixin,DeleteView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model =Animal
    success_url = reverse_lazy('animal_details:index')

class MedicineDetail(LoginRequiredMixin,generic.ListView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model = Medicine
    template_name = 'animal_details/med.html'

class MedicineCreate(LoginRequiredMixin,CreateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model = Medicine
    fields = ['Animal_id', 'Medicine_name', 'Medicine_cost']

class MedicineUpdate(LoginRequiredMixin,UpdateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model = Medicine
    fields = ['Animal_id', 'Medicine_name', 'Medicine_cost']

#-----------------------------------------------------------------------------------------------------------------------

class AccountCreate(LoginRequiredMixin,CreateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model=Accounts
    fields=['Income','Expenditure']

class AccountUpdate(LoginRequiredMixin,UpdateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model=Accounts
    fields=['Income','Expenditure']

class AccountDetail(LoginRequiredMixin,generic.ListView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model=Accounts
    template_name='animal_details/acc.html'

    def get_queryset(self):
        return Accounts.objects.all()

class GrantsCreate(LoginRequiredMixin,CreateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model=Organisation_grants
    fields=['id','Organisation_name','Organisation_phno','Address','Amount']

class GrantsUpdate(UpdateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model=Organisation_grants
    fields=['id','Organisation_name','Organisation_phno','Address','Amount']

class GrantsDetail(LoginRequiredMixin,generic.ListView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model=Organisation_grants
    template_name='animal_details/grant.html'
#-----------------------------------------------------------------------------------------------------------------------
#staff
class StaffCreate(LoginRequiredMixin,CreateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model = Staff
    fields = ['id','Staff_Name','Designation','Salary']
class StaffUpdate(LoginRequiredMixin,UpdateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model = Staff
    fields = ['id','Staff_Name','Designation','Salary']

class StaffDetail(LoginRequiredMixin,generic.ListView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model =Staff
    template_name='animal_details/staff.html'

    def get_queryset(self):
        return Staff.objects.all()

class StaffDelete(LoginRequiredMixin,DeleteView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model=Staff
    success_url = reverse_lazy('animal_details:Staff-detail')




#tourist
class TouristCreate(LoginRequiredMixin,CreateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model = Tourists
    fields = ['id','Tourists_name','Donation','GuideName','Phone_number','Entryfee']

class TouristUpdate(LoginRequiredMixin,UpdateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model = Tourists
    fields = ['id','Tourists_name','Donation','GuideName','Phone_number','Entryfee']
class TouristDelete(LoginRequiredMixin,DeleteView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model = Tourists
    success_url = reverse_lazy('tourists_details:index')
class TouristDetail(LoginRequiredMixin,generic.ListView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model = Tourists
    template_name='animal_details/tourists.html'



class AccountCreate(LoginRequiredMixin,CreateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model=Accounts
    fields=['Income','Expenditure']

class AccountUpdate(LoginRequiredMixin,UpdateView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model=Accounts
    fields=['Income','Expenditure']

class AccountDetail(LoginRequiredMixin,generic.ListView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model=Accounts
    template_name='animal_details/acc.html'

    def get_queryset(self):
        return Accounts.objects.all()

class AccountDelete(LoginRequiredMixin,DeleteView):
    login_url =None
     
    redirect_unauthenticated_users=False
    raise_exception=False
   
    model =Accounts
    success_url = reverse_lazy('animal_details:acc-detail')


class GrantsCreate(LoginRequiredMixin,CreateView):

animal_details/templates/animal_details/account.html
{% load staticfiles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'animal_details/style4.css' %}">

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>



    <div class="container"><a href="#" data-activates="nav-mobile" class="button-collapse top-nav waves-effect waves-light circle hide-on-large-only"><i class="material-icons">menu</i></a></div>
 <ul id="nav-mobile" class="side-nav fixed">
      <!--<ul id="nav-mobile" class="side-nav fixed">-->

     <li class="logo center teal"><a id="logo-container" href="{% url 'animal_details:index' %}" class="brand-logo">
            <object id="front-page-logo" type="" ><i class="material-icons">filter_vintage</i></object></a>
         <h6 class="center white-text"><strong>Prakruthi Sanctuary</strong></h6>
            <br>
     </li>

     <li class="bold"><a href="" class="waves-effect waves-red">Animals</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="" class="waves-effect waves-teal">Employees</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="{% url 'animal_details:Tourist-detail' %}" class="waves-effect waves-red">Tourists</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="{% url 'animal_details:grant-detail' %}" class="waves-effect waves-red">Grants</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="{% url 'animal_details:med-detail' %}" class="waves-effect waves-red">Medicine</a></li>
        <li><div class="divider"></div></li>
        <li class="bold active teal lighten-3"><a href="{% url 'animal_details:acc-detail' %}" class="waves-effect waves-red">Accounts</a></li>
        <li class="bold"><a href="{% url 'animal_details:logout_user' %}" class="waves-effect waves-teal">Log Out</a></li>
        <li><div class="divider"></div></li>
</ul></header>

<main>
    <nav>
        <div class="nav-wrapper center red z-depth-3">
            <a href="{% url 'animal_details:acc-detail' %}" class="brand-logo center">Accounts Details</a>

        </div>
    </nav>
  <br>
    <a href="{% url 'animal_details:account-add' %}" class="btn btn-large waves-effect waves-light teal right z-depth-4"><i class="material-icons left">add</i>Update Account</a>
    <br>
    <br>
    <br>
    <br>


<div class="container">

  <table class="striped centered responsive-table">
     <thead>
       <tr>
          <th>Id</th>
          <th>Date</th>
          <th>Income</th>
          <th>Expenditure</th>

       </tr>
     </thead>
     <tbody>
     {% for accounts in new_account %}
      <tr>
          <td>{{accounts.id}}</td>
          <td>{{accounts.Date}}</td>
          <td>{{accounts.Income}}</td>
          <td>{{accounts.Expenditure}}</td>

      </tr>
     {% endfor %}
     </tbody>
  </table>
</div>
</main>

 <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script>  $(".button-collapse").sideNav({menuWidth:200,});</script>

animal_details/templates/animal_details/index1.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
   <link rel="stylesheet" href="./Materialise css_files/materialize.min.css">
         
    

 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
 <link rel="stylesheet" type="text/css" href="{% static 'animal_details/style3.css' %}">


<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

</head>
<body>
<header>


<div class="container"><a href="#" data-activates="nav-mobile" class="button-collapse top-nav waves-effect waves-light circle hide-on-large-only"><i class="material-icons">menu</i></a></div>
 <ul id="nav-mobile" class="side-nav fixed">
      
         <li class="logo center teal white-text"><a id="logo-container" href="/" class="brand-logo">
            <object id="front-page-logo" type="" ><i class="material-icons">filter_vintage</i></object></a>
         <h6 class="center"><strong>Prakruthi Sanctuary</strong></h6>
            <br>
     </li>

        <li class="bold active teal lighten-3"><a href="{% url 'animal_details:index' %}" class="waves-effect waves-teal">Animals</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="{% url 'animal_details:med-detail' %}" class="waves-effect waves-teal">Medicine</a></li>
        
        <li><div class="divider"></div></li>
        <li class="bold"><a href="{% url 'animal_details:Tourist-detail' %}" class="waves-effect waves-teal">Tourists</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="{% url 'animal_details:Staff-detail' %}" class="waves-effect waves-teal">Employees</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="{% url 'animal_details:grant-detail' %}" class="waves-effect waves-teal">Grants</a></li>
        <li><div class="divider"></div></li>
        <li class="bold"><a href="{% url 'animal_details:acc-detail' %}" class="waves-effect waves-teal">Accounts</a></li>
        
        <li><div class="divider"></div></li>
        <li class="bold"><a href="{% url 'animal_details:logout_user' %}" class="waves-effect waves-teal">Log Out</a></li>
        <li><div class="divider"></div></li>


        
        
</ul></header>


        <!--<li class="logo"><a id="logo-container" href="/" class="brand-logo">
            <object id="front-page-logo" type="image/svg+xml" data="res/materialize.svg">Your browser does not support SVG</object></a></li>
        <li class="search">
          <div class="search-wrapper card">
            <input id="search"><i class="material-icons">search</i>
            <div class="search-results"></div>
          </div>
        </li>
        <li class="bold"><a href="about.html" class="waves-effect waves-teal">About</a></li>
        <li class="bold"><a href="getting-started.html" class="waves-effect waves-teal">Getting Started</a></li>
        <li class="no-padding">
          <ul class="collapsible collapsible-accordion">
            <li class="bold"><a class="collapsible-header  waves-effect waves-teal">CSS</a>
              <div class="collapsible-body">
                <ul>
                  <li><a href="color.html">Color</a></li>
                  <li><a href="grid.html">Grid</a></li>
                  <li><a href="helpers.html">Helpers</a></li>
                  <li><a href="media-css.html">Media</a></li>
                  <li><a href="pulse.html">Pulse</a></li>
                  <li><a href="sass.html">Sass</a></li>
                  <li><a href="shadow.html">Shadow</a></li>
                  <li><a href="table.html">Table</a></li>
                  <li><a href="css-transitions.html">Transitions</a></li>
                  <li><a href="typography.html">Typography</a></li>
                </ul>
              </div>
            </li>
            <li class="bold"><a class="collapsible-header  waves-effect waves-teal">Components</a>
              <div class="collapsible-body">
                <ul>
                  <li><a href="badges.html">Badges</a></li>
                  <li><a href="buttons.html">Buttons</a></li>
                  <li><a href="breadcrumbs.html">Breadcrumbs</a></li>
                  <li><a href="cards.html">Cards</a></li>
                  <li><a href="chips.html">Chips</a></li>
                  <li><a href="collections.html">Collections</a></li>
                  <li><a href="footer.html">Footer</a></li>
                  <li><a href="forms.html">Forms</a></li>
                  <li><a href="icons.html">Icons</a></li>
                  <li><a href="navbar.html">Navbar</a></li>
                  <li><a href="pagination.html">Pagination</a></li>
                  <li><a href="preloader.html">Preloader</a></li>
                </ul>
              </div>
            </li>
            <li class="bold"><a class="collapsible-header  waves-effect waves-teal">JavaScript</a>
              <div class="collapsible-body">
                <ul>
                  <li><a href="carousel.html">Carousel</a></li>
                  <li><a href="collapsible.html">Collapsible</a></li>
                  <li><a href="dialogs.html">Dialogs</a></li>
                  <li><a href="dropdown.html">Dropdown</a></li>
                  <li><a href="feature-discovery.html">FeatureDiscovery</a></li>
                  <li><a href="media.html">Media</a></li>
                  <li><a href="modals.html">Modals</a></li>
                  <li><a href="parallax.html">Parallax</a></li>
                  <li><a href="pushpin.html">Pushpin</a></li>
                  <li><a href="scrollfire.html">ScrollFire</a></li>
                  <li><a href="scrollspy.html">Scrollspy</a></li>
                  <li><a href="side-nav.html">SideNav</a></li>
                  <li><a href="tabs.html">Tabs</a></li>
                  <li><a href="transitions.html">Transitions</a></li>
                  <li><a href="waves.html">Waves</a></li>
                </ul>
              </div>
            </li>
          </ul>
        </li>
        <li class="bold"><a href="mobile.html" class="waves-effect waves-teal">Mobile</a></li>
        <li class="bold"><a href="showcase.html" class="waves-effect waves-teal">Showcase</a></li>
        <li class="bold"><a href="themes.html" class="waves-effect waves-teal">Themes<span class="new badge"></span></a></li>
      -->
      <!--<a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>-->
        
    

<!--<div class="fixed-announcement">
        <div class="announcement">
          <div class="container center">-->
<div style="background-image: url("images/background.jpg");">
<main>

    <!-- <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Animals</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
       
        <li><a href="collapsible.html">Add Animal</a></li>
      </ul>
    </div>
  </nav>-->
  <br>
  <div class="row">
  	<div class="col s3 offset-s9">
        <a href="{% url 'animal_details:animal-add' %}" class="waves-effect waves-light btn z-depth-4"><i class="material-icons right">add</i>
        Add Animal</a>
       </div>
   </div>

  <div class="row">
  	
  		 {% for animal in animals %}

        <div class="col s4">
          <div class="card  teal">
          	<div class="card-image">
          		<img src="{{ animal.Animal_image.url }}" class="img-responsive" width="200" height="250" >
             
            </div>
            <div class="card-content black-text">
              <span class="card-title">{{animal.Animal_species}}</span>
             </div> 
              
            
            <div class="row">
              <div class="left col s2"><a class="waves-effect waves-light btn teal lighten-2  z-depth-4" href="{% url 'animal_details:detail' animal.id %}"><div class="black-text">View</div></a></div>
             
               <div class="col s2 offset-s4"><a href="{% url 'animal_details:animal-update' animal.id %}" class="btn-floating waves-effect waves-light green "><i class="large material-icons">create</i></a></div>
              <div class="right col s2"><a href="{% url 'animal_details:animal-delete' animal.id %}" class="btn-floating red "><i class="large material-icons">delete</i></a></div>
            </div>

              
              
              
              
             
            
           
             
            
          </div>
        </div>
        {% endfor %}

    </div>

  </main>
</div>
         


<!--<h3>Animals in Sanctary are:</h3>
    <ul>
        {% for animal in animals %}
        <div class="row">
        	<div class="col s4 ">
        		<div class=card>
            <li><a href="{% url 'animal_details:detail' animal.id %}">{{animal.Animal_species}}</a>
            </li>
        </div>
    </div>
</div>
        {% endfor %}
    </ul>-->
<!--</div>
</div>
</div>-->

 <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script>  $(".button-collapse").sideNav({ menuWidth: 200,}
);</script>
   


      </body>
</html>